from __future__ import annotations

import csv
import hashlib
import io
import json
import statistics
from pathlib import Path
from typing import Any, Callable

from .meter import measure_call
from .models import CapabilityManifest, Surface
from .util import MinExError, sha256_json


def _first_input(context: dict[str, Any], preferred: list[str]) -> Any:
    for key in preferred:
        if key in context:
            return context[key]
    raise MinExError(f"Missing input. Expected one of: {', '.join(preferred)}")


def text_stats(context: dict[str, Any], _: dict[str, Any]) -> dict[str, Any]:
    text = str(_first_input(context, ["text.raw", "content.text"]))
    words = text.split()
    lines = text.splitlines()
    return {
        "text.stats": {
            "characters": len(text),
            "words": len(words),
            "lines": len(lines),
            "unique_words": len({word.lower().strip(".,;:!?()[]{}\"'") for word in words if word}),
        }
    }


def extractive_summary(context: dict[str, Any], options: dict[str, Any]) -> dict[str, Any]:
    text = str(_first_input(context, ["text.raw", "content.text"]))
    sentence_limit = int(options.get("sentences", 5))
    normalized = text.replace("\n", " ").strip()
    sentences = []
    current = []
    for char in normalized:
        current.append(char)
        if char in ".!?。！？":
            sentence = "".join(current).strip()
            if sentence:
                sentences.append(sentence)
            current = []
    if current:
        sentence = "".join(current).strip()
        if sentence:
            sentences.append(sentence)
    summary = " ".join(sentences[:sentence_limit]) if sentences else normalized[:1200]
    return {"text.summary": summary}


def normalize_json(context: dict[str, Any], _: dict[str, Any]) -> dict[str, Any]:
    raw = _first_input(context, ["json.raw", "content.json"])
    value = json.loads(raw) if isinstance(raw, str) else raw
    return {"json.normalized": json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))}


def sha256_artifact(context: dict[str, Any], _: dict[str, Any]) -> dict[str, Any]:
    value = _first_input(context, ["artifact.bytes", "text.raw", "json.normalized", "report.markdown"])
    payload = value if isinstance(value, bytes) else str(value).encode("utf-8")
    return {"artifact.sha256": hashlib.sha256(payload).hexdigest()}


def csv_profile(context: dict[str, Any], _: dict[str, Any]) -> dict[str, Any]:
    raw = _first_input(context, ["csv.text", "csv.path"])
    text = str(raw)
    if isinstance(raw, str) and "\n" not in raw and len(raw) < 4096:
        try:
            candidate = Path(raw)
            if candidate.is_file():
                text = candidate.read_text(encoding="utf-8")
        except OSError:
            # Treat malformed or overlong path-like inputs as inline CSV text.
            text = str(raw)
    rows = list(csv.DictReader(io.StringIO(text)))
    headers = list(rows[0].keys()) if rows else []
    numeric: dict[str, list[float]] = {key: [] for key in headers}
    for row in rows:
        for key in headers:
            try:
                numeric[key].append(float(row.get(key, "")))
            except (TypeError, ValueError):
                pass
    stats = {}
    for key, values in numeric.items():
        if values:
            stats[key] = {
                "count": len(values),
                "min": min(values),
                "max": max(values),
                "mean": statistics.fmean(values),
            }
    return {"table.profile": {"rows": len(rows), "columns": headers, "numeric": stats}}


def compose_markdown(context: dict[str, Any], options: dict[str, Any]) -> dict[str, Any]:
    title = str(options.get("title", "Verified Capability Brief"))
    parts = [f"# {title}", ""]
    if "text.summary" in context:
        parts += ["## Summary", "", str(context["text.summary"]), ""]
    if "text.stats" in context:
        parts += ["## Text statistics", "", "```json", json.dumps(context["text.stats"], ensure_ascii=False, indent=2), "```", ""]
    if "table.profile" in context:
        parts += ["## Table profile", "", "```json", json.dumps(context["table.profile"], ensure_ascii=False, indent=2), "```", ""]
    parts += ["## Provenance", "", "Generated by a deterministic local MINEX capability route.", ""]
    return {"report.markdown": "\n".join(parts)}


HANDLERS: dict[str, Callable[[dict[str, Any], dict[str, Any]], dict[str, Any]]] = {
    "text_stats": text_stats,
    "extractive_summary": extractive_summary,
    "normalize_json": normalize_json,
    "sha256_artifact": sha256_artifact,
    "csv_profile": csv_profile,
    "compose_markdown": compose_markdown,
}


def execute_capability(capability: CapabilityManifest, context: dict[str, Any]) -> dict[str, Any]:
    kind = str(capability.executor.get("kind", "proposal_only"))
    if kind != "builtin":
        return {
            "status": "PROPOSAL_ONLY_EXECUTOR_NOT_ACTIVE",
            "capability_id": capability.capability_id,
            "surface": capability.surface,
            "external_action_authority": 0,
        }
    handler_name = str(capability.executor.get("handler", ""))
    handler = HANDLERS.get(handler_name)
    if not handler:
        raise MinExError(f"Unknown builtin handler: {handler_name}")
    output, measurement = measure_call(lambda: handler(context, dict(capability.executor.get("options", {}))))
    return {
        "status": "COMPLETED_LOCAL_REVERSIBLE",
        "capability_id": capability.capability_id,
        "outputs": output,
        "measurement": measurement.to_dict(),
        "output_digest": sha256_json(output),
        "deterministic": capability.deterministic,
        "external_action_authority": 0,
    }


def execute_route(
    capabilities: list[CapabilityManifest],
    inputs: dict[str, Any],
    *,
    catalog_map: dict[str, CapabilityManifest] | None = None,
    _recipe_stack: tuple[str, ...] = (),
) -> dict[str, Any]:
    """Execute a local, reversible route.

    A distilled recipe may refer to already registered capabilities. Recipes never
    add authority: every expanded step is re-evaluated by the caller's planner and
    must be present in ``catalog_map``. Recursive or malformed recipes fail closed.
    """
    context = dict(inputs)
    steps: list[dict[str, Any]] = []
    for capability in capabilities:
        missing = set(capability.requires) - set(context)
        if missing:
            raise MinExError(f"Capability {capability.capability_id} missing runtime inputs: {sorted(missing)}")

        kind = str(capability.executor.get("kind", "proposal_only"))
        if kind == "recipe":
            if catalog_map is None:
                result = {
                    "status": "PROPOSAL_ONLY_RECIPE_CATALOG_REQUIRED",
                    "capability_id": capability.capability_id,
                    "external_action_authority": 0,
                }
            elif capability.capability_id in _recipe_stack:
                raise MinExError(f"Recursive recipe detected: {capability.capability_id}")
            else:
                recipe_ids = [str(x) for x in capability.executor.get("steps", [])]
                if not recipe_ids:
                    raise MinExError(f"Recipe {capability.capability_id} has no steps")
                try:
                    expanded = [catalog_map[item] for item in recipe_ids]
                except KeyError as exc:
                    raise MinExError(f"Recipe references unknown capability: {exc.args[0]}") from exc
                nested = execute_route(
                    expanded,
                    context,
                    catalog_map=catalog_map,
                    _recipe_stack=_recipe_stack + (capability.capability_id,),
                )
                result = {
                    "status": nested["status"],
                    "capability_id": capability.capability_id,
                    "recipe_steps": recipe_ids,
                    "expanded_steps": nested.get("steps", []),
                    "outputs": nested.get("outputs", {}),
                    "output_digest": nested.get("route_output_digest"),
                    "external_action_authority": 0,
                }
        else:
            result = execute_capability(capability, context)

        steps.append(result)
        if result["status"] != "COMPLETED_LOCAL_REVERSIBLE":
            return {
                "status": "PROPOSAL_ONLY_ROUTE_NOT_EXECUTED",
                "steps": steps,
                "context_keys": sorted(context),
                "external_action_authority": 0,
            }
        context.update(result.get("outputs", {}))
    return {
        "status": "COMPLETED_LOCAL_REVERSIBLE",
        "steps": steps,
        "outputs": context,
        "route_output_digest": sha256_json(context),
        "external_action_authority": 0,
    }
